# Generated by Django 5.0.7 on 2024-08-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
                ("picture", models.FileField(upload_to="picture")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.book"
                    ),
                ),
            ],
            options={
                "db_table": "pictures",
            },
        ),
    ]
