# Generated by Django 5.0.7 on 2024-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApp", "0001_add_student_school_pref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("authors", models.ManyToManyField(to="ModelApp.authors")),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
