# Generated by Django 5.0.7 on 2024-08-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApp", "0001_add_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="created_at",
            new_name="create_at",
        ),
    ]
