# Generated by Django 5.0.7 on 2024-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormApp", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("grade", models.IntegerField()),
                ("picture", models.FileField(upload_to="exam/%Y/%m/%d")),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.FileField(upload_to="picture/%Y/%m/%d"),
        ),
    ]
