# Generated by Django 5.0.7 on 2024-08-24 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("user", "zip_code", "prefecture", "address")},
        ),
    ]
