# Generated by Django 5.0.7 on 2024-08-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
        migrations.AlterModelTable(
            name="item",
            table="item",
        ),
    ]
